[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/upload"
  to   = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/api/photos"
  to   = "/.netlify/functions/photos"
  status = 200
